name: Limpeza Automática da Memória

on:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 3h UTC (00h no Brasil)
  workflow_dispatch:      # Permite execução manual via GitHub

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências do projeto
        run: npm install

      - name: Executar limpeza de memória
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node scripts/memoryManager.mjs
